### ISSUE TITLE
Add mappers when building products in facto.

### ISSUE THREAD

**Issue by larrymjordan** [wawandco/facto#12]
Hi guys, good morning. Not sure if this will be out of the scope for facto, but here I go.

I was spending some time using facto and I probably noticed a common use case in some of the unit tests I've being working on. This common use case I’m referring to is that one where I found myself applying some repeated transformations to the `Product` object after it gets created by facto.  

**What kind of transformation do I mean?** 
things like parsing the object to a JSON format, parse them to a CSV  or transform object fields into url values for example.

### About
 This proposal is about adding the ability  to facto  to use "mappers" in the process of building a product. What do I mean with mappers? Well, basically this idea is brought out by the `map` function defined in Javascript arrays. The map function allows to return a new different array by applying some transformation to each element inside of it. 

I have examples bellow where I illustrate this idea based on the scenarios I faced with:

### Scenario 1

> "I would like to make a POST request using the product object in a JSON format  when exercising my test case".

Inside facto we would implement a predefined mapper function that facilitates the task:

```go
jsonUser := facto.Build(UserFactory, facto.JSONMapper).([]byte)
// jsonUser => `{"Name":"Wawandco 0"}`
...
http.Post(url, “application/json”, jsonUser) 
```

`JSONMapper` would take product returned by `userFactory` and map it into a JSON formatted slice of bytes product.

This would also work for multiple Products when using `BuildN` function.

```go
jsonUsers := facto.BuildN(UserNFactory, 5, facto.JSONMapper).([]byte)
// jsonUsers => `[{"Name":"Wawandco 0"},{"Name":"Wawandco 1"},{"Name":"Wawandco 2"},{"Name":"Wawandco 3"},{"Name":"Wawandco 4"}]`
...
http.Post(url, “application/json”, jsonUser) 
```

By taking the idea of map function from javascript, a `MapperFn` in facto is a function that takes a `Product` and returns the Product transformed:

```go 
 type func MapperFn(Product) Product
```

`Build` function would also need to be redefined as a variadic function. This allows multiple mappers to be called in a chain-like fashion. Scenario 2 bellow illustrate this.

```go
func Build(f Factory, mappers ...MapperFn) Product
func BuildN(f Factory, n int, mappers ...MapperFn) Product
```

### Scenario 2

> I would like to create an object on my database and parse it into a JSON format when setting up my test case.

```go
myDBMapper := func(p Product) Product {
    ...
     u := p.(User)
     err := dbConn.Create(&u)
    // assert err is not null.
    return Product(u)
}

body := facto.Build(userFactory, myDBMapper, facto.JSONMapper).([]byte)
...
```

Here, mappers act like a chain of transformations, meaning the product returned by `myDBMapper` becomes the input product for JSONMapper. 

Facto could implement some mappers function commonly used in testing scenarios. Here is a list of some mapper functions I think could be defined inside facto package:

**JSON Mapper**: Maps a Product object into a formatted JSON slice bytes product.
**Form Mapper**: Maps a Product object into a `url.Values`.
**URLEncoded Mapper**: Maps a Product object into a `url.Values` object.
**YAML Mapper**: Maps a Product object into a YAML object.
**CSV Mapper**: Maps a Product object into a CSV slice bytes product.

### Advantages
Some advantages I foresee based on the problem it solves
  - Adds a transformation layer to facto when building a Product.
  - It provides more dynamism to facto when creating a product through a factory.
  - Mappers can be extended and developers can define their own.
  - Allows reuse transformations commonly applied through testing life cycle.

### Disadvantages
Here are some Disadvantages I foresee that could be a blocker to implement.   

- From an end user experience, it is not really obvious when using a mapper what is the expected type object returned that you need to cast.
- From a maintenance  perspective, It increases the level of dependencies with external packages that helps to solve the mapping transformation (toml, yaml, csv).
- Mappers chain are executed in the same order as specified in the arguments, this could bring unexpected behavior if one mapper of that chain does not support the product type received.

Thank you for reading this proposal and let me know your thoughts about this cc @paganotoni @amartine59 @rdiazrovira @EdwinPB

**Comment by paganotoni** [comment]
Hey @larrymjordan, Its great that you're starting to use Facto! Love it! I also appreciate you've put proposal in this way, it lays out the idea very well.

Getting into the idea I have to disagree with adding that in the build/buildN methods. And I think in general this kind of expands the use case of facto. Let me expand a bit more in here.

The use case for Facto is to build/create objects that we will need use for testing purposes.

I think the proposal expands that into transforming Go objects into something else, which is more of a data transformation and manipulation process (I receive A pass it through B and C and get D).

Also, the proposed implementation violates the SRP for the mappers, the proposed method signature receives those mappers (I would call them transformers but .. you know  😅 ) and now not only has to build the object but transform it, breaking the SRP for what they say to do (`build` and `buildN`).
